### ISSUE TITLE
Unable to run the programme

### ISSUE THREAD

**Issue by Captfan** [xtsoukala/dual_path#14]
Hi,

I've tried to run the programme but failed.

I've installed Python 3.8.3, and installed the required modules:

matplotlib==3.2.1
numpy==1.18.5
pandas==1.0.4
seaborn==0.10.1
torch==1.5.1
scipy==1.4.1
lz4==3.1.0
scikits.bootstrap==1.0.1
joblib==0.15.1

However, when entering following command in CMD:

python3 src/start_dual_path.py --sim 4 --aux --hidden 80 --compress 60 

It didn't return results as expected, but return to the command line again. Similar situation happened when entering the command:

python3 src/start_dual_path.py -h 

Would you please give me a hind on hot to run the programme?

**Comment by xtsoukala** [comment]
Hi,

Thank you for your interest in the model! I’m currently using Python 3.7.4 (on Ubuntu and Mac OS), I hadn’t tested it with the latest Python version. I created just now a virtual environment with 3.8.3 and tried to install requirements.txt. It seems to fail at the installation of PyTorch, because, apparently, there is no compatibility (yet?) with Python 3.8.

The error I got was: 
ERROR: Could not find a version that satisfies the requirement torch==1.3.1 (from -r requirements.txt (line 5)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.4.0, 1.5.0, 1.5.1)
ERROR: No matching distribution found for torch==1.3.1 (from -r requirements.txt (line 5))

One (complex) solution is to install the version 1.3.1 from source:
https://github.com/pytorch/pytorch#from-source

But the easiest solution is to install python 3.7 or to simply install the latest PyTorch version via, for instance, “pip install torch”. Note that most computations in the model are done with torch tensors, so there is a chance that using a different version will lead to small (but hopefully not susceptible) differences in the results compared to the ones I have reported. I see that the latest Pytorch version throws a warning (FutureWarning: pickle support for Storage will be removed in 1.5. Use `torch.save` instead) but it otherwise runs fine.

I also noticed that “pip install -r requirements.txt” is designed to stop if even a single package fails. In this case, it is better to install them one by one using:

cat requirements.txt | xargs -n 1 pip install

It's also best if you "git pull" the latest changes because we are editing the message-sentence generator at the moment and I think that the version you cloned may time out and exit with an error.

Just to give you an indication of how long the script will take to run: I have a Macbook pro mid-2014 with 4 cores (2,8 GHz i5) and 8GB DDR3. Running 2 networks (model runs) with the "code-switching" mode on ( python3 src/start_dual_path.py --sim 2 --cs ) takes 13' on my laptop (about the same time it takes to run 40 simulations on the server).

Let me know if the issue persists!
Chara

**Comment by Captfan** [comment]
Hello Chara,

Thank you very much for your reply.

I had an error when installing torch. So what I did is:

I went to PyTorch, from its Get Started page (https://pytorch.org/get-started/locally/), I selected

PyTorch Build: Stable (1.5.0)  Note: it is now 1.5.1
Your OS: Windows
Package: Pip
Language: Python
CUDA: 10.2

Then the command for installation will be generated, which successfully installed pytorch after downloading a pretty big whl file, about 900 MB.

So I think that's the latest PyTorch version installed as you suggested?

If the programme is not compatible with Python 3.8, then I will try to install Python 3.7.4.

With kind regards,

Fan

**Comment by Captfan** [comment]
Hello Chara,

Follow your previous suggestions, I've installed Python 3.7.4 (64-bit) and installed all required packages.

Just would like you know that as I don't have Nvidia GPU for my laptop, so I install the PyTorch with no CUDA.

I can run the simulation OK, but I have to change the command from python3 to python. So when running:

python src/start_dual_path.py --sim 4 --aux --hidden 80 --compress 60 

I have:

Simulation 1: L1 decimal fraction: 0.37, L2 decimal fraction: 0.63
Simulation 2: L1 decimal fraction: 0.53, L2 decimal fraction: 0.47
Simulation 3: L1 decimal fraction: 0.36, L2 decimal fraction: 0.64
Simulation 4: L1 decimal fraction: 0.5, L2 decimal fraction: 0.5

Then there is an error message:

UnicodeEncodeError: 'gbk' codec can't encode character '\xf1' in position 5: illegal multibyte sequence

I think due to this error, I didn't get any simulation results although simulation folder were created with 5 folders in it, named "1", "2", "3", "4", and "input", but there is no csv file as mentioned in your instruction.

Do you mind to give another hand here? Sorry if this is due to my lack of sufficient knowledge in python.

With kind regards,

Fan

For your reference, here are all the messages received:

C:\Python\dual_path-master>python src/start_dual_path.py --sim 4 --aux --hidden 80 --compress 60
Simulation 1: L1 decimal fraction: 0.37, L2 decimal fraction: 0.63
Simulation 2: L1 decimal fraction: 0.53, L2 decimal fraction: 0.47
Simulation 3: L1 decimal fraction: 0.36, L2 decimal fraction: 0.64
Simulation 4: L1 decimal fraction: 0.5, L2 decimal fraction: 0.5
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\joblib\externals\loky\process_executor.py", line 431, in _process_worker
    r = call_item()
  File "C:\Python\Python37\lib\site-packages\joblib\externals\loky\process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "C:\Python\Python37\lib\site-packages\joblib\_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "C:\Python\Python37\lib\site-packages\joblib\parallel.py", line 253, in __call__
    for func, args, kwargs in self.items]
  File "C:\Python\Python37\lib\site-packages\joblib\parallel.py", line 253, in <listcomp>
    for func, args, kwargs in self.items]
  File "C:\Python\dual_path-master\src\modules\corpus_generator.py", line 67, in create_input_for_simulation
    test_set, training_set = self.generate_general()
  File "C:\Python\dual_path-master\src\modules\corpus_generator.py", line 93, in generate_general
    test_set = self.generate_sentences(sentence_structures_test, fname="test.in")
  File "C:\Python\dual_path-master\src\modules\corpus_generator.py", line 228, in generate_sentences
    self.save_language_sets(fname, generated_pairs)
  File "C:\Python\dual_path-master\src\modules\corpus_generator.py", line 234, in save_language_sets
    f.write(u'%s## %s\n' % (sentence, message))
UnicodeEncodeError: 'gbk' codec can't encode character '\xf1' in position 5: illegal multibyte sequence
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/start_dual_path.py", line 287, in <module>
    Parallel(n_jobs=-1)(delayed(input_sets.create_input_for_simulation)(sim, ) for sim in simulation_range)
  File "C:\Python\Python37\lib\site-packages\joblib\parallel.py", line 1042, in __call__
    self.retrieve()
  File "C:\Python\Python37\lib\site-packages\joblib\parallel.py", line 921, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\Python\Python37\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\Python\Python37\lib\concurrent\futures\_base.py", line 435, in result
    return self.__get_result()
  File "C:\Python\Python37\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
UnicodeEncodeError: 'gbk' codec can't encode character '\xf1' in position 5: illegal multibyte sequence

**Comment by xtsoukala** [comment]
Hi Fan,

Thank you for sending detailed logs and for installing Python 3.7! It should work with version 3.8 as well but it's indeed better to run the model without the warning messages from PyTorch. I don't use CUDA either so this shouldn't be an issue. Unfortunately, I've only tested the model on Mac OS and Ubuntu so I've never encountered the issue you mentioned. Given that it's an encoding problem, I've pushed a bugfix to explicitly set the encoding to utf-8 when opening a file. This could potentially solve the issue on Windows. Could you "git pull" the changes and check if the simulations run correctly? If you encounter more issues, I'll install a Windows virtual machine to see where the script fails. 

Chara

**Comment by Captfan** [comment]
Hi Chara,

Thanks for your quick reply. Really appreciate your help. I've downloaded the latest version and run the simulation again. Unfortunately there is still similar issue (despite the torch.save warning as you previously mentioned).

Here I attached are all the messages for your reference:

C:\Python\dual_path-master>python src/start_dual_path.py --sim 4 --aux --hidden 80 --compress 60

Simulation 1: L1 decimal fraction: 0.37, L2 decimal fraction: 0.63
Simulation 2: L1 decimal fraction: 0.53, L2 decimal fraction: 0.47
Simulation 3: L1 decimal fraction: 0.36, L2 decimal fraction: 0.64
Simulation 4: L1 decimal fraction: 0.5, L2 decimal fraction: 0.5
C:\Python\Python37\lib\site-packages\torch\storage.py:34: FutureWarning: pickle support for Storage will be removed in 1.5. Use `torch.save` instead
  warnings.warn("pickle support for Storage will be removed in 1.5. Use `torch.save` instead", FutureWarning)
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\joblib\externals\loky\process_executor.py", line 431, in _process_worker
    r = call_item()
  File "C:\Python\Python37\lib\site-packages\joblib\externals\loky\process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "C:\Python\Python37\lib\site-packages\joblib\_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "C:\Python\Python37\lib\site-packages\joblib\parallel.py", line 253, in __call__
    for func, args, kwargs in self.items]
  File "C:\Python\Python37\lib\site-packages\joblib\parallel.py", line 253, in <listcomp>
    for func, args, kwargs in self.items]
  File "C:\Python\dual_path-master\src\modules\dual_path.py", line 297, in start_network
    self.inputs.update_sets(f"{self.inputs.root_directory}/{simulation_num}")
  File "C:\Python\dual_path-master\src\modules\formatter.py", line 137, in update_sets
    self.event_sem_activations['training'], self.target_lang_act['training']) = self.read_set_to_df()
  File "C:\Python\dual_path-master\src\modules\formatter.py", line 514, in read_set_to_df
    df['target_sentence_idx'] = df.target_sentence.apply(self.sentence_indices)
  File "C:\Python\Python37\lib\site-packages\pandas\core\series.py", line 3848, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas\_libs\lib.pyx", line 2329, in pandas._libs.lib.map_infer
  File "C:\Python\dual_path-master\src\modules\formatter.py", line 577, in sentence_indices
    return list(map(self.lexicon_index.__getitem__, sentence.split()))
KeyError: '茅l'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/start_dual_path.py", line 331, in <module>
    Parallel(n_jobs=-1)(delayed(dualp.start_network)(sim, ) for sim in simulation_range)
  File "C:\Python\Python37\lib\site-packages\joblib\parallel.py", line 1042, in __call__
    self.retrieve()
  File "C:\Python\Python37\lib\site-packages\joblib\parallel.py", line 921, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\Python\Python37\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\Python\Python37\lib\concurrent\futures\_base.py", line 435, in result
    return self.__get_result()
  File "C:\Python\Python37\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
KeyError: '茅l'

**Comment by Captfan** [comment]
Hi Chara,

Hope you are doing well. Sorry to trouble you again.

I am still working on your programme. I've installed Ubuntu 20.04 and installed Python 3.7.9 and all required packages sucessfully.

The only issue I have when running the simulation is: **ValueError: The truth value of a DataFrame is ambiguous.**

I don't know if you will be able to help me identify the issues? Thank you.

With kind regards,

Fan

Here attached all the error messages I've received for your reference:

joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/fan/.local/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/home/fan/.local/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/fan/.local/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 608, in __call__
    return self.func(*args, **kwargs)
  File "/home/fan/.local/lib/python3.8/site-packages/joblib/parallel.py", line 255, in __call__
    return [func(*args, **kwargs)
  File "/home/fan/.local/lib/python3.8/site-packages/joblib/parallel.py", line 255, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/fan/Downloads/dual_path-master/src/modules/dual_path.py", line 308, in start_network
    self.inputs.update_sets(f"{self.inputs.root_directory}/{simulation_num}")
  File "/home/fan/Downloads/dual_path-master/src/modules/formatter.py", line 164, in update_sets
    self.allowed_structures = self.read_allowed_pos()
  File "/home/fan/Downloads/dual_path-master/src/modules/formatter.py", line 564, in read_allowed_pos
    self.trainlines_df.target_pos if self.trainlines_df else self.testlines_df))))
  File "/home/fan/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 1329, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/start_dual_path.py", line 357, in <module>
    Parallel(n_jobs=-1)(delayed(dualp.start_network)(sim, ) for sim in simulation_range)
  File "/home/fan/.local/lib/python3.8/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/fan/.local/lib/python3.8/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/fan/.local/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

**Comment by xtsoukala** [comment]
Hi Fan! I'm really sorry for neglecting to look into the Windows installation; I think it was encoding-related but I postponed setting up a Windows VM. Anyway, I checked the DataFrame issue and I just pushed the bugfix. I also updated some required versions in requirements.txt because they were outdated, but that shouldn't affect your current setup. 

I ran 4 simulations on my laptop and it took 15' to train and test; I noticed, however, that logging (i.e., seeing error messages/the progress) doesn't work properly, I'll look into that. 

Also, if you want to run a generic code-switching simulation, it's best if you run:

python3 src/start_dual_path.py --sim 4 --cs

because the --aux flag is for the auxiliary phrase asymmetry simulation. Given that you seem interested in the model, I'll look into updating the readme file and documenting it better. 

Let me know if you have more questions and thanks again for checking it out!

Chara

**Comment by Captfan** [comment]
Hello Chara,

No worries and thank you very much for looking into the issue and provide updates.

I've run the programme successfully, that's wonderful. I've got various csv files including all_results.csv, code-switch_types.csv, performance.csv and performance_per_lang.csv. I will take a look of the simulation results in more detail.

By the way, at the end of the simulation, there is a future warning regarding pandas.np module, I think it may of interest to you.

/home/fan/Downloads/dual_path-master/src/modules/plotter.py:391: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  plt.yticks(pd.np.arange(0, ylim + 1, step=10))
/home/fan/Downloads/dual_path-master/src/modules/plotter.py:393: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  xticks = pd.np.arange(df.epoch.min(), df.epoch.max() + 1, step=2)

Again, thank you very much for your time and effort.

With kind regards,

Fan

**Comment by xtsoukala** [comment]
Perfect, let me know if you want help setting up your own experiments or analyzing the output!

Thank you for the future warning too, I've fixed it (you can "git pull" the changes if you want). 

Kind regards,
Chara
